### ISSUE TITLE
python pip package

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/libCombine#10]
Hi all,
is it possible to provide a python pip package for libCombine (similar to python-libnuml, python-libsedml).

The best
Matthias

**Comment by matthiaskoenig** [comment]
Hi Frank, 
could you upload the pip package? This would help a lot.
The best 
Matthias

**Comment by fbergmann** [comment]
hello matthias, I've uploaded a pip package ... can you give it a try? I'll be working on binary wheels sometime soon

**Comment by matthiaskoenig** [comment]
Hi Frank,
thanks for this. Everything works.
I just updated the python examples using the pip package.
M
