### ISSUE TITLE
Content of manifest.xml is not accessible

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/libCombine#16]
The content of the manifest.xml is not accesible, i.e., the following does not 
give any content when done on the entry for the manifest.xml:
```
archive.extractEntry(entry.getLocation(), <filename or folder>)
content = archive.extractEntryToString(entry.getLocation());
```

**Comment by fbergmann** [comment]
This is on purpose ... the manifest just represents all the content in the combine archive. Any modification of the combine archive would invalidate whatever was previously in the manifest. Thus currently, as soon as the archive is read ... all the manifest entries are internalized and then discarded. This way once the archive is saved again the *current* state of the archive is saved as the new manifest file. After all there cannot be more than one manifest in the archive. 

so what would you expect to happen ... and what would be the usecase? I only see downsides of keeping an old manifest around ... 

if you convince me, I could serialize whatever the current manifest is and *pretend* it would be the current archive entry ... but that would be a hack that i'd rather avoid

**Comment by matthiaskoenig** [comment]
Thanks, this clears things up.
I mainly want to be able to see the content of the archive, i.e. the file content when selecting them. But probably it is better to open the archive with a zip library for that. 
I thought of libcombine as a zip library with the manifest on top of it. I think I just misunderstood what entry means, i.e. that it is an entry managed via the manifest vs. content in the zip file.
So nothing to do here. Thanks for clearing this up.
