### ISSUE TITLE
Metadata should be named 'metadata.rdf' not 'metadata.xml'

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/libCombine#18]
Currently, the metadata is stored in the zip file under `metadata.xml`, but the specification states this file should be named `metadata.rdf` 

From combine archive specification:

> Finally associated meta information for clerical data is included in location="metadata.rdf".

**Comment by fbergmann** [comment]
metadata like anything else in the COMBINE archive is matched by its type ... so its name should not be relevant at all. I can rename it if you like but it won't have any influence for consuming libraries.

**Comment by matthiaskoenig** [comment]
I would prefer if it could be renamed to `metadata.rdf`. The other tools working with combine archives all write `metadata.rdf` files (and probably also look for this in the archive to read the metadata). Examples are JWS or the SEMS tools.

**Comment by fbergmann** [comment]
Remember, that there can be multiple metadata files in the archive ... so any name is valid as long as the type is correctly set. I'm debugging as to what is going on with the JWS one. Just in case here the extract from the spec (section 3.3 content of the archive): 


```2. metadata files containing clerical information about the various files contained in the archive, and the archive itself. A best practice is to include only one file for each file format metadata called metadata.* (where * means the suitable file extension) ```
