### ISSUE TITLE
Add __version__ variable to python bindings

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/libCombine#2]
It would be nice to have a

```
libcombine.__version__
```

variable.
This makes it easy to collect all the **version** of the libraries I am using via a script.

**Comment by 0u812** [comment]
👍 for this. The `__version__` attribute is suggested in [PEP0396](https://www.python.org/dev/peps/pep-0396/). Unfortunately, the PEP is deferred, but there is no other standard for specifying the version of a Python package AFAIK.

**Comment by fbergmann** [comment]
will be added with the next release.

**Comment by fbergmann** [comment]
the version attribute is now checked in

**Comment by matthiaskoenig** [comment]
thanks.
