### ISSUE TITLE
libCombine java bindings for Mac and Linux

### ISSUE THREAD

**Issue by gmarupilla** [sbmlteam/libCombine#30]
I have an issue with the "libcombine_java" java library, the current release is built only on windows and doesn't have libraries (native libraries) included for Linux(combinej.so) and Mac(combined.dynlib). Is there any chance of a new version with Mac and Linux libraries??

**Comment by fbergmann** [comment]
of course, i'll try and get one done within the next two days, i'll announce it here just in case.

**Comment by gmarupilla** [comment]
That would be really helpful. Thanks for quick response

**Comment by fbergmann** [comment]
I've just released a new version, the archive now includes binaries for linux and mac

**Comment by gmarupilla** [comment]
Thank you 😊
