### ISSUE TITLE
Provide distribution for Linux / x64 / Python 3.8

### ISSUE THREAD

**Issue by jonrkarr** [sbmlteam/libCombine#37]
libCOMBINE is missing a PyPI distribution for Linux / x64 / Python 3.8. @fbergmann could you add this?

**Comment by fbergmann** [comment]
@jonrkarr i've just uploaded the latest py38 version it is `0.2.11`, is there a reason you have to remain pinned to `0.2.9`?

**Comment by matthiaskoenig** [comment]
Perfect, works for me. 
Thanks, can be closed.

**Comment by jonrkarr** [comment]
0.2.9 was just an example. I don't see a need for py 3.8 versions of the earlier releases.
