### ISSUE TITLE
How can OMEX manifest files be directly read and written?

### ISSUE THREAD

**Issue by jonrkarr** [sbmlteam/libCombine#42]
To my knowledge, libCOMBINE can read and write OMEX manifest files, but only part of COMBINE archives. In some cases, it is useful to be able to work with OMEX manifest files directly. For example, in the BioModels cleanup project we want to store the contents of COMBINE archives unpacked into directories so we can version control their changes.

**Comment by fbergmann** [comment]
i've added an example on how to read / write manifest files directly

**Comment by jonrkarr** [comment]
Copying links to the examples here for anyone searching the GitHub issues about the same question
- [`add_to_manifest.py`](https://github.com/sbmlteam/libCombine/blob/master/examples/python/add_to_manifest.py)
- [`read_manifest.py`](https://github.com/sbmlteam/libCombine/blob/master/examples/python/read_manifest.py)
