### ISSUE TITLE
CombineArchive::extractTo(const std::string&) does not appear to extract correctly

### ISSUE THREAD

**Issue by CodeByDrescher** [sbmlteam/libCombine#59]
During patching of Biosimulation's Biosimulator_Utils, a bug was discovered where combine archive contents were extracted as directories rather than as files (if curious, see: [Biosimulators_utils/blob/dev/biosimulators_utils/combine/io.py](https://github.com/biosimulators/Biosimulators_utils/blob/dev/biosimulators_utils/combine/io.py) Line: 209). Calls traced back to libCombine, and potentially Zipper. 

Archive tested had a manifest and two empty files as content, it looks like the manifest extracted correctly, but the two empty files became directories. The archive is synthetic and not practical, but it was used for testing and used to extract properly.

see attached:
[archive.zip](https://github.com/sbmlteam/libCombine/files/10170438/archive.zip)

**Comment by fbergmann** [comment]
This is indeed a problem with zipper, where entries of size 0 are interpreted as directories. I'll have a look to see what can be changed.
