### ISSUE TITLE
zipper not found despite providing ZIPPER_LIBRARY and ZIPPER_INCLUDE_DIR

### ISSUE THREAD

**Issue by agarny** [sbmlteam/libCombine#63]
Say that you configure libCOMBINE as a static library and pass it a value for both `ZIPPER_LIBRARY` and `ZIPPER_INCLUDE_DIR`. Well, despite that, CMake will complain about `ZIPPER::ZIPPER` not being found. I have fixed it [here](https://github.com/opencor/libCombine/commit/b58b14f09d514f754a84ccb00872b2e303a8724b) in my fork of libCOMBINE.

FWIW, I also had to pass a value for an XML parser (`libxml2` in my case) as seen [here](https://github.com/opencor/libCombine/commit/adea20374568782b5a1f570417efd0b1688cdbe9). Without that I get told that some libxml2 methods are undefined (e.g., `_xmlCreatePushParserCtxt`).

Happy to create a PR, if you want. Just let me know.

**Comment by fbergmann** [comment]
Thanks for letting me know. I'll have a look. Thanks for letting me know. The build system might need updating to allow for the automatic dependency tracking. If the libSBML target is imported, it should already have all the information about the needed XML parser included. I'll have to debug where that is coming from. I might need a week or two for this tho.

**Comment by agarny** [comment]
Don't worry about it, I have a working solution, so no rush.
