### ISSUE TITLE
Python bindings: Support adding file contents as string?

### ISSUE THREAD

**Issue by 0u812** [sbmlteam/libCombine#8]
Hi Frank,
In the documentation, the method `addFile` of the `CombineArchive` class has two signatures. The second signature takes a std::istream to support adding files from memory. However, I'm not sure if it is possible to use this from the Python bindings. Would it be possible to add a method, e.g. `addFileFromString`, which takes a string representing the file contents as the first argument?

**Comment by fbergmann** [comment]
This is implemented with the commit from above, please let me know whether you need anything else.

**Comment by 0u812** [comment]
Perfect! Thanks so much!
